### ISSUE TITLE
Create loop function to loop through the different sorting functions

### ISSUE THREAD

**Issue by Daniel-Halls** [WMDA/social-media-analysis#16]
I think it would be a good idea if everytime the pipeline ran it ran by new, then controversial etc. Would be good for the cloud function. If we can incorporate the remove duplicate function so we don't save any duplicates.  

##I think once this is done we should start to run the pipeline to collect the data. We can still work on the pipeline to improve it while collecting the data##

**Comment by Kiki-Jiji** [comment]
I don't think this is needed. The aim is to collect the entire subbredit (starting from when we start GCP), therefore new is sufficient as this will order them by date, and we will every day collect all the submissions, so new/hot etc will just be duplicates. Think that's right?
Agree we should start the data ingest

**Comment by Daniel-Halls** [comment]
Fair enough. Closed
